// <auto-generated />
namespace TodoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Todo11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Todo11));
        
        string IMigrationMetadata.Id
        {
            get { return "201903110334510_Todo11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
